include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/BackendHelpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/MpFree.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Muphasa.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/FunctionDelaunay.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Graphcode.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DegRips.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/MultiCritical.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/TwoPac.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/RhomboidTiling.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Aida.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Hera.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/PersistenceAlgebra.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Skyscraper.cmake")
