include("${CMAKE_CURRENT_LIST_DIR}/BackendHelpers.cmake")
multipers_create_backend(hera)
if(EXISTS "${MULTIPERS_HERA_SOURCE_DIR}/include/hera/matching_distance.h")
  target_include_directories(${MULTIPERS_BACKEND_TARGET} INTERFACE "${MULTIPERS_HERA_SOURCE_DIR}/include")
  if(EXISTS "${MULTIPERS_HERA_SOURCE_DIR}/extern/phat/boundary_matrix.h")
    target_include_directories(${MULTIPERS_BACKEND_TARGET} BEFORE INTERFACE "${MULTIPERS_HERA_SOURCE_DIR}/extern")
  endif()
  target_link_libraries(${MULTIPERS_BACKEND_TARGET} INTERFACE multipers::tbb multipers::phat)
endif()
