if(NOT DEFINED REPO_ROOT)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs REPO_ROOT")
endif()
if(NOT DEFINED OVERLAY_ROOT)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs OVERLAY_ROOT")
endif()
if(NOT DEFINED LIBRARY_NAME)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs LIBRARY_NAME")
endif()
if(NOT DEFINED LIBRARY_RELATIVE_ROOT)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs LIBRARY_RELATIVE_ROOT")
endif()
if(NOT DEFINED PATCH_FILES)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs PATCH_FILES")
endif()
string(REPLACE "::" ";" PATCH_FILES "${PATCH_FILES}")
list(LENGTH PATCH_FILES _num_patches)
if(_num_patches EQUAL 0)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs at least one PATCH_FILE")
endif()
if(NOT DEFINED PATCH_EXECUTABLE)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs PATCH_EXECUTABLE")
endif()
if(NOT DEFINED STAMP_FILE)
  message(FATAL_ERROR "ApplyExtPatchOverlay.cmake needs STAMP_FILE")
endif()

file(REMOVE_RECURSE "${OVERLAY_ROOT}")
set(_source_files "")

# Copy only files named by patches. Unmodified vendored files fall through to
# the original checkout include roots, while these exact files shadow them.
foreach(patch_file IN LISTS PATCH_FILES)
  if(NOT EXISTS "${patch_file}")
    message(FATAL_ERROR "Missing ${LIBRARY_NAME} patch ${patch_file}")
  endif()
  file(STRINGS "${patch_file}" _patch_headers REGEX "^[-+][-+][-+] ")
  foreach(header_line IN LISTS _patch_headers)
    string(REGEX REPLACE "^[^ ]+ " "" _patch_path "${header_line}")
    string(REGEX REPLACE "[\t ].*$" "" _patch_path "${_patch_path}")
    if(_patch_path STREQUAL "/dev/null")
      continue()
    endif()
    string(REGEX REPLACE "^[ab]/" "" _relative_path "${_patch_path}")
    if(NOT _relative_path MATCHES "^${LIBRARY_RELATIVE_ROOT}/")
      message(FATAL_ERROR
        "${LIBRARY_NAME} patch ${patch_file} references unexpected path ${_relative_path}")
    endif()
    set(_source_path "${REPO_ROOT}/${_relative_path}")
    if(EXISTS "${_source_path}")
      list(APPEND _source_files "${_source_path}")
    endif()
  endforeach()
endforeach()
list(REMOVE_DUPLICATES _source_files)

foreach(source_file IN LISTS _source_files)
  file(RELATIVE_PATH _relative_path "${REPO_ROOT}" "${source_file}")
  get_filename_component(_destination_parent "${OVERLAY_ROOT}/${_relative_path}" DIRECTORY)
  file(MAKE_DIRECTORY "${_destination_parent}")
  file(COPY "${source_file}" DESTINATION "${_destination_parent}")
endforeach()

foreach(patch_file IN LISTS PATCH_FILES)
  execute_process(
    COMMAND "${PATCH_EXECUTABLE}" -p1 -i "${patch_file}"
    WORKING_DIRECTORY "${OVERLAY_ROOT}"
    RESULT_VARIABLE patch_result
    OUTPUT_VARIABLE patch_stdout
    ERROR_VARIABLE patch_stderr
  )
  if(NOT patch_result EQUAL 0)
    message(FATAL_ERROR
      "Failed to apply ${LIBRARY_NAME} patch ${patch_file}.\nstdout:\n${patch_stdout}\nstderr:\n${patch_stderr}")
  endif()
endforeach()

file(WRITE "${STAMP_FILE}" "${LIBRARY_NAME} patch overlay ready\n")
if(DEFINED DEPFILE)
  file(WRITE "${DEPFILE}" "${STAMP_FILE}: ${_source_files} ${PATCH_FILES}\n")
endif()
